In [1]:
import cv2
import numpy as np

In [5]:
canvas = np.zeros((512,512,3),dtype="uint8")
print(canvas)

cv2.imshow("Image",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

Qt: Session management error: Could not open network socket
QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QO

In [8]:
canvas = np.zeros((512,512,3)) + 255
print(canvas)
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the 

In [9]:
  # Line çizimi yapma
canvas = np.zeros((512,512,3)) + 255
print(canvas)
cv2.line(canvas,(0,0),(512,512),(0,0,0), thickness=5)
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the 

In [10]:
canvas = np.zeros((512,512,3)) + 255
print(canvas)
cv2.line(canvas,(0,0),(512,512),(0,0,0), thickness=1) # thickness kalıklık
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the 

In [ ]:
canvas = np.zeros((512,512,3)) + 255
print(canvas)
cv2.line(canvas,(50,50),(50,100),(0,0,0), thickness=4) # thickness kalıklık
cv2.line(canvas,(50,50),(100,50),(0,0,0,),thickness=4)
cv2.line(canvas,(100,50),(100,100),(0,0,0,),thickness=4)
cv2.line(canvas,(100,100),(50,100),(0,0,0,),thickness=4)
# linelardan kare yapmak
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)

cv2.destroyAllWindows()

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the object's thread (0xfd87a10).
Cannot move to target thread (0x101610b0)

QObject::moveToThread: Current thread (0x101610b0) is not the 

In [3]:
# Dikdörtgen çizme
import cv2
import numpy as np
canvas = np.zeros((512,512,3))+255

cv2.rectangle(canvas, (50,50),(150,150),(0,0,255),thickness=4)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

Qt: Session management error: Could not open network socket
QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToT

In [4]:
import cv2
import numpy as np
canvas = np.zeros((512,512,3))+255

cv2.rectangle(canvas, (50,50),(152,170),(0,0,255),thickness=4)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [5]:
import cv2
import numpy as np
canvas = np.zeros((512,512,3))+255

cv2.rectangle(canvas, (50,50),(152,170),(0,0,255),thickness=-1) # içini doldurma

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [8]:
# Daire çizme merkez noktası yarıçap
canvas = np.zeros((512,512,3))+255

cv2.circle(canvas,(250,250),50,(0,255,0),thickness=5)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [9]:
# Daire çizme merkez noktası yarıçap
canvas = np.zeros((512,512,3))+255

cv2.circle(canvas,(250,250),50,(255,255,0),thickness=-1)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [10]:
# Daire çizme merkez noktası yarıçap
canvas = np.zeros((512,512,3))+255

cv2.circle(canvas,(500,500),50,(255,255,0),thickness=4)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [14]:
# Üçgen oluşturma özel bir fonksiyon yok biz çizgilerle oluşturabiliriz
canvas = np.zeros((512,512,3)) + 255

cv2.line(canvas,(50,50),(150,150),(255,0,0),thickness=3)
cv2.line(canvas,(150,150),(150,80),(255,0,0),thickness=3)
cv2.line(canvas,(150,80),(50,50),(255,0,0),thickness=3)


cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [16]:
canvas = np.zeros((312,312,3)) + 255

cv2.line(canvas,(100,100),(254,259),(0,0,0),thickness=5)
cv2.line(canvas,(254,259),(120,4),(0,0,0,),thickness=5)
cv2.line(canvas,(120,4),(100,100),(0,0,0),thickness=5)

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [22]:
# çok kenarlı gen oluşturma

canvas = np.zeros((512,512,3)) + 255

points = np.array([[110,200],[400,500],[124,180],[400,400]],np.int32)


cv2.polylines(canvas,[points],True,(0,0,255),thickness=5)  # true değeri kapalı yapar 

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [30]:
# ellipse oluşturma
canvas = np.zeros((512,512)) + 255

cv2.ellipse(canvas, (250,250),(100,150),20,0,360,(0,0,0),thickness=5)
# ilk değer merkez ikinci değer genişil yükseklik ,eğim , başlangıç açısı, bitiş açısı , renk , kalınlık

cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [31]:
canvas = np.zeros((512,512)) + 255
cv2.ellipse(canvas, (250,250),(100,150),20,0,260,(0,0,0),thickness=5)
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [32]:
canvas = np.zeros((512,512)) + 255
cv2.ellipse(canvas, (250,250),(150,150),20,0,360,(0,0,0),thickness=5)
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [37]:
# Yazı Yazdırma
canvas = np.zeros((512,512)) + 255

font1 = cv2.FONT_HERSHEY_COMPLEX
font2 = cv2.FONT_HERSHEY_DUPLEX
font3 = cv2.FONT_HERSHEY_SCRIPT_SIMPLEX


cv2.putText(canvas,"Merhaba",(120,120),font1,3,(0,0,0),cv2.LINE_AA)
# ilk kordinat metnin başlayacağı sol alt kordinat
# yazı tipi seçiyorsun



cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [43]:
# Yazı Yazdırma
canvas = np.zeros((512,512)) + 255

font1 = cv2.FONT_HERSHEY_COMPLEX
font2 = cv2.FONT_HERSHEY_DUPLEX
font3 = cv2.FONT_HERSHEY_SCRIPT_SIMPLEX


cv2.putText(canvas,"Merhaba",(120,120),font3,4,(0,0,0),cv2.LINE_AA)
# ilk kordinat metnin başlayacağı sol alt kordinat
# yazı tipi seçiyorsun



cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread

In [ ]:
# Yazı Yazdırma
canvas = np.zeros((512,512)) + 255


cv2.putText(canvas,"Merhaba",(120,120),cv2.FONT_ITALIC,4,(0,0,0),cv2.LINE_AA)
# ilk kordinat metnin başlayacağı sol alt kordinat
# yazı tipi seçiyorsun



cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread (0x35bdbc0).
Cannot move to target thread (0x369ae30)

QObject::moveToThread: Current thread (0x369ae30) is not the object's thread